
theme: jekyll-theme-slate
title: 神眼堪舆明师
description: 风水改命-阴宅-阳宅-禅定培训-驻颜术-健康管理
email:      renboxi@gmail.com
url: 
copyright:
year:       2022
name:       格局上医
google_analytics:
#设置不显示github 图标
github:
  is_project_page: false
  
# 多语言配置
gems:           ['jekyll-multiple-languages']
# 如果需要分页, 请加入 jekyll-paginate 并放于 jekyll-multiple-languages 之前
# gems:           ['jekyll-paginate', 'jekyll-multiple-languages']

# 所有的语言
languages:          ['cn', 'tc']

# 默认语言
# 如果没有配置，languages 中的第一项就是默认语言
language_default:   'cn'
